name: 'Lint'

on:
  workflow_call:

jobs:
  biome:
    runs-on: ubuntu-latest
    name: 'Biome'
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: biomejs/setup-biome@v2
      - run: biome check
