name: 'Lint'

on:
  workflow_call:

jobs:
  biome:
    runs-on: ubuntu-latest
    name: 'Biome'
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
      - uses: biomejs/setup-biome@v2
      - run: biome ci .
