name: 'ðŸ§ª Test'

on:
  workflow_call:

jobs:
  test-generator:
    runs-on: ubuntu-latest
    name: 'Generator Tests'
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: denoland/setup-deno@v2
      - run: deno install && deno test

  test-publishing:
    runs-on: ubuntu-latest
    name: 'Release Tests'
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          path: build
          merge-multiple: true
      - uses: actions/setup-node@v4
        with:
          node-version: 'latest'
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci && npm publish --dry-run --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
